services:
  - type: web
    name: dealnest-backend
    env: python
    region: frankfurt
    plan: free # Explicitly request Free Tier
    buildCommand: "./build.sh"
    startCommand: "gunicorn dealnest.wsgi:application"
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: "*"
